# Generated by Django 4.1.4 on 2023-01-05 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atc_app', '0002_alter_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('logo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('img', models.CharField(max_length=254)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atc_app.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atc_app.collection')),
                ('tools', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atc_app.tool')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='tools',
            field=models.ManyToManyField(through='atc_app.CollectionTools', to='atc_app.tool'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL),
        ),
    ]
